/**
 * Cairn - shell shortcuts (`cairn window` / `cairn tab` / `status` / `list`), ADR-0009.
 *
 * The installer wires a `cairn` shell function into the user's shell profile so the ambient Codex
 * zone display is one short command away - cross-platform:
 *  - Windows: a PowerShell function merged into `$PROFILE` (window = `wt` split-pane, tab = OSC title).
 *  - macOS/Linux: a POSIX function in `~/.config/cairn/cairn.sh`, sourced from `~/.zshrc`/`~/.bashrc`
 *    (window = tmux split / iTerm2 / Terminal.app, tab = OSC title - works in any terminal).
 *
 * The function shadows the `cairn` bin in the shell, so any unrecognised subcommand (install,
 * uninstall, help, …) is forwarded to `node <server.js> …` - the bin keeps working.
 *
 * Everything here is PURE (string in → string out) so it is unit-tested without touching a real HOME
 * or any terminal. The side-effecting file/profile wiring lives in `installer.ts`.
 */

import { t, type Lang } from "../i18n/index.js";

export interface ShortcutPaths {
  /** Absolute path to dist/bin/cairn-codex-watch.js */
  watch: string;
  /** Absolute path to dist/bin/cairn-codex-status.js */
  status: string;
  /** Absolute path to dist/server.js (the real `cairn` bin, for forwarding). */
  server: string;
}

// Same markers in every managed file (profile, rc) - but each file holds at most one block.
export const SHORTCUT_BEGIN = "# >>> cairn >>>";
export const SHORTCUT_END = "# <<< cairn <<<";

/** Insert/replace a marked block in `existing` (idempotent - re-running replaces, never duplicates). */
export function mergeMarked(
  existing: string,
  inner: string,
  begin: string = SHORTCUT_BEGIN,
  end: string = SHORTCUT_END,
): string {
  const block = `${begin}\n${inner}\n${end}`;
  const bi = existing.indexOf(begin);
  if (bi !== -1) {
    const ei = existing.indexOf(end, bi);
    if (ei !== -1) {
      const before = existing.slice(0, bi);
      const after = existing.slice(ei + end.length);
      return (before + block + after).replace(/\n{3,}/g, "\n\n");
    }
  }
  if (existing.trim() === "") return block + "\n";
  const sep = existing.endsWith("\n") ? "\n" : "\n\n";
  return existing + sep + block + "\n";
}

/** Remove the marked block (reverse of mergeMarked). No-op if absent. */
export function unmergeMarked(
  existing: string,
  begin: string = SHORTCUT_BEGIN,
  end: string = SHORTCUT_END,
): string {
  const bi = existing.indexOf(begin);
  if (bi === -1) return existing;
  const ei = existing.indexOf(end, bi);
  const cutEnd = ei === -1 ? existing.length : ei + end.length;
  return (existing.slice(0, bi) + existing.slice(cutEnd)).replace(/\n{3,}/g, "\n\n");
}

/**
 * The PowerShell `cairn` function (Windows). Returned WITHOUT markers - merge with mergeMarked.
 * `$WATCH`/`$STATUS`/`$SERVER` are baked to absolute paths; backslashes are literal in PS strings.
 */
export function psShortcut(p: ShortcutPaths, lang: Lang = "en"): string {
  const m = t(lang).shell;
  return [
    `function cairn {`,
    `  param([Parameter(Position=0)][string]$cmd, [Parameter(ValueFromRemainingArguments=$true)]$rest)`,
    `  if (-not $cmd) { Write-Host "${m.helpLine}"; return }`,
    `  $WATCH  = "${p.watch}"`,
    `  $STATUS = "${p.status}"`,
    `  $SERVER = "${p.server}"`,
    `  switch ($cmd) {`,
    `    'window' { $cwd=(Get-Location).Path; $sh = if (Get-Command pwsh -ErrorAction SilentlyContinue) {'pwsh'} else {'powershell'}; wt -w 0 split-pane -H -s 0.12 -d "$cwd" $sh -NoExit -Command "cairn strip" }`,
    `    'strip'  { node "$WATCH" --print --interval 2 }`,
    `    'tab'    { $global:CairnTitle = Start-Process node -ArgumentList "\`"$WATCH\`"","--interval","2" -NoNewWindow -PassThru; Write-Host "${m.titleRunningPs}" }`,
    `    'stop'   { if ($global:CairnTitle) { Stop-Process -Id $global:CairnTitle.Id -Force -ErrorAction SilentlyContinue; $global:CairnTitle=$null; Write-Host "${m.titleStopped}" } else { Write-Host "${m.noTitleActive}" } }`,
    `    'status' { node "$STATUS" @rest }`,
    `    'list'   { node "$STATUS" --list }`,
    `    default  { node "$SERVER" $cmd @rest }`,
    `  }`,
    `}`,
  ].join("\n");
}

/**
 * The POSIX `cairn` function (macOS/Linux). Returned as the full body of `~/.config/cairn/cairn.sh`
 * (no markers - the whole file is ours). `window` cascades tmux → iTerm2 → Terminal.app → inline;
 * paths are passed to osascript via argv so spaces in the install path are handled correctly.
 */
export function shShortcut(p: ShortcutPaths, lang: Lang = "en"): string {
  const m = t(lang).shell;
  return [
    `# Cairn shell shortcuts (ADR-0009) — generated by 'cairn install'.`,
    `cairn() {`,
    `  WATCH="${p.watch}"`,
    `  STATUS="${p.status}"`,
    `  SERVER="${p.server}"`,
    `  case "$1" in`,
    `    window)`,
    `      _cairn_cmd="node \\"$WATCH\\" --print --interval 2"`,
    `      if [ -n "$TMUX" ]; then`,
    `        tmux split-window -v -l 3 "$_cairn_cmd"`,
    `      elif [ "$TERM_PROGRAM" = "iTerm.app" ]; then`,
    `        osascript - "$WATCH" >/dev/null 2>&1 <<'OSA'`,
    `on run argv`,
    `set w to item 1 of argv`,
    `tell application "iTerm2"`,
    `tell current window`,
    `tell current session`,
    `set s to (split horizontally with default profile)`,
    `tell s to write text ("node " & quote & w & quote & " --print --interval 2")`,
    `end tell`,
    `end tell`,
    `end tell`,
    `end run`,
    `OSA`,
    `      elif [ "$TERM_PROGRAM" = "Apple_Terminal" ]; then`,
    `        osascript - "$WATCH" >/dev/null 2>&1 <<'OSA'`,
    `on run argv`,
    `set w to item 1 of argv`,
    `tell application "Terminal" to do script ("node " & quote & w & quote & " --print --interval 2")`,
    `end run`,
    `OSA`,
    `      else`,
    `        echo "${m.noTmux}"`,
    `        eval "$_cairn_cmd"`,
    `      fi ;;`,
    `    strip)  node "$WATCH" --print --interval 2 ;;`,
    `    tab)`,
    `      node "$WATCH" --interval 2 2>/dev/null &`,
    `      CAIRN_TITLE_PID=$!`,
    `      echo "${m.titleRunningPosix}" ;;`,
    `    stop)`,
    `      if [ -n "$CAIRN_TITLE_PID" ]; then kill "$CAIRN_TITLE_PID" 2>/dev/null; unset CAIRN_TITLE_PID; echo "${m.titleStopped}"; else echo "${m.noTitleActive}"; fi ;;`,
    `    status) shift; node "$STATUS" "$@" ;;`,
    `    list)   node "$STATUS" --list ;;`,
    `    "")     echo "${m.helpLine}" ;;`,
    `    *)      node "$SERVER" "$@" ;;`,
    `  esac`,
    `}`,
  ].join("\n");
}

/** The marked source line for an rc file (`.zshrc`/`.bashrc`) - sources cairn.sh if present. */
export function shSourceInner(cairnShPath: string): string {
  return `[ -f "${cairnShPath}" ] && . "${cairnShPath}"`;
}
